package com.lr.service;

import java.security.GeneralSecurityException;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import com.lr.exceptions.AuthException;
import com.lr.key.ApiKey;


public class AutheticationService {
	
	private static  AutheticationService authService = null;
	
	// A user storage which stores <username, password>
    private final Map<String, String> usersStorage = new HashMap();
 
    // A service key storage which stores <service_key, username>
    private final Map<String, String> serviceKeysStorage = new HashMap();
 
    // An authentication token storage which stores <service_key, auth_token>.
    private final Map<String, String> authorizationTokensStorage = new HashMap();
 
    private AutheticationService() {
        // The usersStorage pretty much represents a user table in the database
        usersStorage.put( "praja", "praja" );
        usersStorage.put( "admin", "admin" );
 
        /**
         * Service keys are pre-generated by the system and is given to the
         * authorized client who wants to have access to the REST API. Here,
         * only username1 and username2 is given the REST service access with
         * their respective service keys.
         */
        serviceKeysStorage.put( "824bb1e8-de0c-401c-9f83-8b1d18a0ca9d", "praja" );
        serviceKeysStorage.put( "e94c0841-927c-4985-bdf0-85015ab063ab", "admin" );
    }
 
    public static AutheticationService getInstance() {
        if ( authService == null ) {
        	authService = new AutheticationService();
        }
 
        return authService;
    }
 
    public String login( String serviceKey, String username, String password ) throws AuthException {
        if ( serviceKeysStorage.containsKey( serviceKey ) ) {
            String usernameMatch = serviceKeysStorage.get( serviceKey );
 
            if ( usernameMatch.equals( username ) && usersStorage.containsKey( username ) ) {
                String passwordMatch = usersStorage.get( username );
 
                if ( passwordMatch.equals( password ) ) {
 
                    /**
                     * Once all params are matched, the authToken will be
                     * generated and will be stored in the
                     * authorizationTokensStorage. The authToken will be needed
                     * for every REST API invocation and is only valid within
                     * the login session
                     */
                    String authToken = UUID.randomUUID().toString();
                    authorizationTokensStorage.put( authToken, username );
 
                    return authToken;
                }
            }
        }
 
        throw new AuthException("Username and Password is not correct");
    }
 
    /**
     * The method that pre-validates if the client which invokes the REST API is
     * from a authorized and authenticated source.
     *
     * @param serviceKey The service key
     * @param authToken The authorization token generated after login
     * @return TRUE for acceptance and FALSE for denied.
     */
    public boolean isAuthTokenValid( String serviceKey, String authToken ) {
        if ( isServiceKeyValid( serviceKey ) ) {
            String userName = serviceKeysStorage.get( serviceKey ); 
            if ( authorizationTokensStorage.containsKey( authToken ) ) { 
                if ( userName.equals( authorizationTokensStorage.get( authToken ) ) ) {
                    return true;
                }
            }
        }
        
        return false;
    }
 
    /**
     * This method checks is the service key is valid
     *
     * @param serviceKey
     * @return TRUE if service key matches the pre-generated ones in service key
     * storage. FALSE for otherwise.
     */
    public boolean isServiceKeyValid( String serviceKey ) {
        return serviceKeysStorage.containsKey( serviceKey );
    }
 
    public void logout( String serviceKey, String authToken ) throws GeneralSecurityException {
        if ( serviceKeysStorage.containsKey( serviceKey ) ) {
            String usernameMatch1 = serviceKeysStorage.get( serviceKey ); 
            if ( authorizationTokensStorage.containsKey( authToken ) ) {
                String usernameMatch2 = authorizationTokensStorage.get( authToken );
 
                if ( usernameMatch1.equals( usernameMatch2 ) ) { 
                    /**
                     * When a client logs out, the authentication token will be
                     * remove and will be made invalid.
                     */
                    authorizationTokensStorage.remove( authToken );
                    return;
                }
            }
        }
        
        throw new GeneralSecurityException( "Invalid service key and authorization token match." );
    }
	
	public static boolean isApiKeyValid(String apiKey) {		
		if ((apiKey == null || apiKey == "")
				|| (apiKey != null
					&& !apiKey.equals(ApiKey.key))) 
		{			
			return false;
		}		
		return true;
	}	

}
